### PR TITLE
Override id and id? methods on the sales entry

### PR DESCRIPTION
**Pull request by LuukvH**
Most resources have an id as primary key. However the sales entry has an EntryId as primary key.
See: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesEntrySalesEntries
This will let the base methods such as save and find work for Sales entries.

### CODE REVIEW

**Comment by LuukvH** [comment]
@Marthyn is this code still maintained?

**Comment by Marthyn** [comment]
@LuukvH  I'm sorry i've not taken a look before but I have now and will merge. Thank you for providing this.

**Comment by Marthyn** [comment]
@LuukvH Very interesting. I think ExactOnline has removed me from their organization and i do not have write access anymore to this repository.

**Comment by Marthyn** [comment]
I made a fork to my personal account now so i could make a new release with your changes. I have maintained the access to the rubygems upload (https://rubygems.org/gems/elmas/versions/3.1.0). Ownership has never been with Exact, the ownership of the repo lies with my former employer (https://github.com/hoppinger). When i left that company we had a mutual agreement that I would keep maintaining the repository when new PR's like this come in. I think for now it's best if you keep using your personal fork/branch. I will contact Exact/Hoppinger about this.

**Pull request closed without merging**
