### PR TITLE
add project and time tracking functionality

### PR DESCRIPTION
**Pull request by mipmip**
this pull request also include a few small fixes in the documentation and the examples in the readme.

### CODE REVIEW

**Comment by Marthyn** [comment]
Awesome! Could you also add some specs for these resources?

**Comment by mipmip** [comment]
here you are

**Comment by Marthyn** [comment]
Awesome sauce! :shipit:

**Comment by Marthyn** [comment]
@mipmip I released a new version of the Gem, we also added some updates for ourselves, like the datetime parsing, it has to be saved in a different format than we get it from ExactOnline. See #6. 
https://rubygems.org/gems/elmas/versions/1.0.0

**Comment by mipmip** [comment]
Very nice.

**Pull request merged**
