### PR TITLE
Use activeresource's ThreadsafeAttributes for thread safe config values

### PR DESCRIPTION
**Pull request by korstiaan**
This PR proposes using Rails' activeresource's `ThreadsafeAttributes` to make this gem thread safe.

### CODE REVIEW

**Comment by Marthyn** [comment]
Looking good @korstiaan, any reason why this is still WIP? Cause otherwise i can merge and release a new version.

**Comment by korstiaan** [comment]
@Marthyn we'll have to wait for the `activeresource` maintainers to merge my PR on the 4-stable branche. It's only merged in master now, which requires Rails' activesupport > 5.0.0

**Comment by Marthyn** [comment]
@korstiaan Whats the status on this PR?

**Comment by Marthyn** [comment]
@korstiaan Whats the status on this PR?

**Pull request merged**
