### PR TITLE
Add date to BaseEntryLine, which is parent for GeneralJournalEntryLin…

### PR DESCRIPTION
**Pull request by pieterb82**
BaseEntryLine is the parent class for GeneralJournalEntryLine, as this doesn't have other attributes I added it to the BaseEntryLine as other attribute. 

https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=GeneralJournalEntryGeneralJournalEntryLines

### CODE REVIEW

**Comment by pieterb82** [comment]
@Marthyn is it possible to process this request??

**Comment by Marthyn** [comment]
Of course! The PR missed my attention.

**Comment by pieterb82** [comment]
@Marthyn thanks, yes the very nice update of ExactOnline with the regeneration of refreshtokens on each request right? Which still isn't live as of yet.

**Comment by Marthyn** [comment]
@pieterb82 
3.0.0 was released and deprecates the OAUTH authorization methods because 2factor authentication was enforced.
3.1.0 I just released which just really removes the deprecated methods and gives more insight into bad request exceptions (Exact sends an error message that the gem ignored before).

The regeneration of refresh tokens is something that the implementation of the Gem has to do, not the gem itself. For one of our projects at Hoppinger we created some code that refreshes the refresh_token and makes sure the old refresh_token is then replaced and never used twice. We do this also by using locking. The code I cannot share unfortunately, because it's part of a closed source system. 

I still wish Exact would implement a server to server authentication method 🤷‍♂️

**Comment by pieterb82** [comment]
@Marthyn Ah ok, sorry wasn't with you on the deprecated methods, which is now clear. 

For other integration we setup such a server as well where we can fetch the lastest refreshtoken. Will implement code to fetch the token from there and use that in this integration. 

Thanks for adding the request again!

**Pull request merged**
